### ISSUE TITLE
coverage histogram causes malformedBedLineError

### ISSUE THREAD

**Issue by radaniba** [daler/pybedtools#110]
Hello

I am trying to create a histogram using pybedttols and coverage wrapper but when I look at the result (the header) it looks fine except the option `hist` cause the MalformedBedLineError since it is a not a valid bed file

here is the error message

```
>>> for position in coverage:
...     if(position[0]=="all"):
...             print position
...
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cbedtools.pyx", line 680, in pybedtools.cbedtools.IntervalFile.__next__ (pybedtools/cbedtools.cpp:8685)
pybedtools.cbedtools.MalformedBedLineError: malformed line: ['all', '0', '981', '30513', '0.0321502']
```

my command to get the coverage was : 

```
coverage = alignment.coverage(regions, hist=True)
```

Any idea on how to get only the `all` lines ?

Thanks

**Comment by adomingues** [comment]
Hi @daler 
 I've just hit up a little snag with this issue, that is the output of coverageBed not being a bed - which is fine. To cut a long story short, I wanted to convert this output into a bed file to use in other operations (closest). So I was calculating coverage:
 
 ```python
import pybedtools
in_reads = pybedtools.example_bedtool('x.bam')
strand = '+'
three_bg = in_reads.genome_coverage(dz=True, strand=strand, **{'3': True})
```

And created a function, `cov2bed6` that with the help of `extend_fields ` and `show_value` would change this:
>  chr2L   4999310   1

to this:

> chr2L   4999310   4999311   .   1    +

However, since `three_bg` is not a proper bed it whole thing just crashed and burn. Do you happen to know of a handy solution to convert the coverage output into bed? Otherwise I will just wrangle something with Pandas.

Out of interest, the `cov2bed6` looks like this:


```python
def cov2bed6(bg, strand):
    """
    Converts single nucleotide coverage (bedTool):
    chr2L   4999307 1
    chr2L   4999308 1
    chr2L   4999310 1

    to bed6 (bedTool) in which the score is put in 5th field. The name is set to ".". If no strand is provided - not recommend! - "." is the default.
    Returns a bedTool obj
    """
    assert strand is "+" or strand is "-" or strand is "."
    bead4 = bg.each(add_end).saveas()
    stranded = bead4.each(add_strand, strand).saveas()
    bed6 = stranded.each(update_score).saveas()
    return bed6
```

**Comment by daler** [comment]
Yep, in this case I would switch to pandas for the manipulation and conversion into a BED-like format.

**Comment by adomingues** [comment]
Just in case someone needs a similar solution, here is my function to convert coverage (chr position score) into bed4:

```
def coverage_to_bedTool(cov):
    """
    Converts single nucleotide coverage (bedTool):
    chr2L   4999307 1
    chr2L   4999308 1
    chr2L   4999310 1

    to bed4 (bedTool). This step is needed because bedTools expects col2 < col3 which is not always the case since col3 is the coverage. The end coordinate is position (col2) + 1. See:
    https://github.com/daler/pybedtools/issues/145
    https://github.com/daler/pybedtools/issues/110
    https://github.com/daler/pybedtools/issues/112

    Returns a bedTool obj
    Requires pandas.
    """
    df = pd.read_table(cov.fn, names=['chrom', 'start', 'coverage'])
    df['end'] = df['start'] + 1
    df = df[['chrom', 'start', 'end', 'coverage']]
    bed4 = pybedtools.BedTool.from_dataframe(df)
    return bed4
```

Btw, and out of curiosity, even though `cov.head()` returns a "malformedBedLineError" message, `cov.tail()` works fine. Just use my previous example and see the difference between  `three_bg.tail()` and `three_bg.head()`.

**Comment by daler** [comment]
Thanks.

The different `head()` and `tail()` behavior is from `head` doing the easy thing -- "for i in bedtool; print(i)" -- while `tail` breaks the last bytes of the file off into chunks to find the newlines to avoid having to iterate over the entire file.

After thinking about it, it probably makes sense to have `head` work on the file directly just like `tail` does so that debugging the MalformedBedLineError messages would be easier. I'll open an issue for that.

And seeing the issues referenced in your docstring reminds me that it hasn't been just one person hitting the assumption that coverage output is a BED file. So maybe it's worth adding something like you've shown as a helper function.  Does this make sense as a method on a BedTool object? Or a function in the `helpers` module?

**Comment by adomingues** [comment]
> Does this make sense as a method on a BedTool object? Or a function in the helpers module?

I would probably make it a `helpers` function because it is very case-specific for _some_ of the coverage files, and it could keep the class as is. If anyone needs to change format, it would simply all the function and all would be good. But you know more about the specific of the BedTool objects.

**Comment by daler** [comment]
It might be convenient to include in a "pipeline" like:

```python
x = (
    BedTool('a.bam')
    .genome_coverage(dz=True)
    .coverage_to_bed()
    .intersect('b.bed')
)
```
In which case being a method would be the way to go. I was just checking out `helpers.py` and it doesn't make sense with the other kinds of functions there.

**Comment by adomingues** [comment]
You are probably right. I was thinking more along lines of functions like `pybedtools.featurefuncs.three_prime`.

Thank you once again for being so damn fast fixing things.
