### ISSUE TITLE
small error in cat()

### ISSUE THREAD

**Issue by michael-imbeault** [daler/pybedtools#138]
I'm concatenating bedtools with bedtool.cat(*[bedtools]) and it works fine, except that everything gets truncated to BED3 even with force_truncate=False and postmerge=False.

I tracked down the issue to a small mistake in cat() (at bedtool.py line 2690):

field_nums = set([i.field_count for i in other_beds]).difference([None])

Turns out that i.field_count doesn't return the count, it returns the method. It should be field_count() instead. Also you might want to add [self.field_count()] just as the type. So the final would be:

field_nums = set(self.field_count() + [i.field_count() for i in other_beds]).difference([None])

Thanks,
Michael

**Comment by daler** [comment]
Thanks Michael. Good catch, I made that change.

While I was fixing this, I also made `BedTool.cat` work so that if the field lengths don't match but `force_truncate` and `postmerge` are False, then the output will contain the minimum number of fields observed across all inputs, rather than always truncating to BED3. But if filetypes don't match (like from catting GFF and BED), or force_truncate=True, then output will be BED3.

The new docs and tests in 80c09ca reflect this -- can you see if this solves the issue for you?

**Comment by michael-imbeault** [comment]
It does - I tested it locally before submitting the issue. Thanks for the quick fix!
