### ISSUE TITLE
__add__ method of class BedTool (line 1106 in bedtool.py)

### ISSUE THREAD

**Issue by danhalligan** [daler/pybedtools#141]
It is possible for result to be undefined within the following function causing an error:

    def __add__(self, other):
        try:
            result = self.intersect(other, u=True)
        except BEDToolsError:
            # BEDTools versions <2.20 would raise BEDToolsError
            if (self.file_type == 'empty') or (other.file_type == 'empty'):
                result = pybedtools.BedTool("", from_string=True)
        return result

This happens if an exception is raised and the condition in the except clause is not met.
See also issue [github.com/chapmanb/bcbio-nextgen#1002](https://github.com/chapmanb/bcbio-nextgen/issues/1002).

**Comment by daler** [comment]
If an exception is raised when trying to intersect and it's not a `BEDToolsError`, that exception won't be caught and should be raised. Somehow what's happening here is that there's no exception, yet `result` isn't being created.

I'm unable to reproduce.  I've tried the following, which all works as expected:

```python

def test_issue_141():
    a = pybedtools.example_bedtool('a.bed')
    b = pybedtools.example_bedtool('b.bed')

    # make an empty file
    empty = pybedtools.BedTool("", from_string=True)

    # invalid file format
    malformed = pybedtools.BedTool('a	a	a', from_string=True)

    # positive control; works
    a + b

    # "adding" an empty file always gets zero features
    assert len(a + empty) == 0
    assert len(empty + a) == 0
    assert len(empty + empty) == 0

    # "adding" a malformed file raises MalformedBedLineError
    # (an uncaught exception raised when trying to intersect)
    a + malformed
```

Are you able to find a minimal example that reproduces this error?

Adding `result = None` as the first line of the `__add__` method which would solve the `UnboundLocalError` issue but would then cause problems downstream because a `None` is returned. I'd like to figure out why this is happening, and return an appropriate value. For example, should `result` default to an empty file? Or have a check at the end to see if `result is None`, in which case an exception is raised, like `WrongInputError` or something?

cc @chapmanb and @schelhorn

**Comment by chapmanb** [comment]
Ryan;
Thanks for looking at this, it's really helpful. We're having trouble coming up with a small test case now so this discussion and testing on what could be wrong is so helpful. I won't dig into empty or misformed files anymore since those aren't triggering it. What cases does pybedtools raise `BEDToolsError` when doing an intersection? We're getting it for something that is not an empty file (or your workaround would catch it). If we have other ideas about what could cause this we could try to come up with a minimal case, or fix the underlying issue in bcbio. Thanks again.

**Comment by daler** [comment]
Hi Brad - 

Let's see . . . `BEDToolsError` will be raised:

- if a bedtools program can't support BAM input [[source]](https://github.com/daler/pybedtools/blob/master/pybedtools/bedtool.py#L261)

- if the called program isn't available [[source]](https://github.com/daler/pybedtools/blob/master/pybedtools/helpers.py#L250)

- if there's unhandled stderr upon calling a bedtools program [[source]](https://github.com/daler/pybedtools/blob/master/pybedtools/helpers.py#L378)

Looks like that stack trace over in https://github.com/chapmanb/bcbio-nextgen/issues/1002 is doing something in parallel, which makes debugging tricky.  Is this doing something with BAMs? I'm using pysam rather than wrapping samtools stdout in the latest pybedtools (v0.7.0), which might be causing some other issues, especially if something is happening on the cython side of pysam.

Other than the hunches of "something something parallel and/or bam", I'm stumped at the moment. Sorry I don't have more specific ideas. I'll keep thinking about it.

**Comment by chapmanb** [comment]
Ryan;
Thanks for this, that's really helpful. We're not dealing with BAM files here so I'd imagine it's from an unhandled stderr condition. Dan, do you see this error consistently when re-running bcbio? I've recently run into bedtools IO errors when accessing shared files on a distributed file system, so know there can be some instability there. This part of the code isn't especially parallel since it deals with merging a bunch of files produced by a previous parallel run so it shouldn't be hitting disk too hard. Thanks again for the help debugging.

**Comment by danhalligan** [comment]
Hi Brad - I'll try re-running when I get chance and see if the error is reproducible at the same stage, hopefully this should shed some light, however, its on a system with direct attached storage and fast disks, so it seems unlikely that we have trouble reading the files. Thanks!

**Comment by chapmanb** [comment]
Ryan and Dan -- just to follow up on this I finally identified the underlying issue. The intersect in `__add__` was failing on hg38 chromosome names due to the naming checking inside bedtools. Calling intersection explicitly and adding `nonamecheck=True` solved the underlying issue.

Ryan,  it would be useful to re-raise the bedtools std error if you can't identify the cause when checking this, but otherwise pybedtools is doing the right thing and we're just dealing with the new and messy world of hg38. Thanks again for all the help debugging.

**Comment by daler** [comment]
Brad, thanks for the follow-up. I'll make sure pybedtools propagates the error up to save this sort of headache in the future.

**Comment by danhalligan** [comment]
Thanks guys.

**Comment by daler** [comment]
Brad - do you have a test-case I could use in regression tests? I'm having trouble reproducing.

**Comment by daler** [comment]
Ah, thanks. I haven't worked much with hg38 yet and my shortcut using UCSC's `fetchChromSizes hg38` didn't return any HLA names . . . so I wasn't sure what you meant.

These examples definitely reproduce, and I'll work on the fix.

**Comment by daler** [comment]
pybedtools was already doing the right thing by raising a `BEDToolsError` but -- stupidly -- I didn't re-raise the exception in the `__add__` method.

I should have caught that immediately but didn't for some reason, causing extra work for everyone involved. I'm really sorry about that.
