### ISSUE TITLE
Versions on PyPi and Conda out of date

### ISSUE THREAD

**Issue by dgaston** [daler/pybedtools#152]
PyPi seems to be at 0.71 and Conda at 0.72. Not sure if the releases 0.73 and 0.74 which both seem to have been put out on Oct 31 are both new actual releases or not.

**Comment by daler** [comment]
Thanks for reporting this.

0.7.3 is a "ghost" release -- I had upload problems to PyPI, but then it wouldn't let me fix the upload. So it needed another version bump.

0.7.4 is a bug fix (mostly for your other issue #147). It wasn't on PyPI, but I just uploaded it. Thanks for the reminder. I've also updated the [changelog](http://daler.github.io/pybedtools/changes.html) in the docs.

I've been working a lot on the [bioconda](https://github.com/bioconda/recipes) repo which is where v0.7.4 has been living since Oct 31. I've updated the pybedtools docs [install page](http://daler.github.io/pybedtools/main.html) to reflect the new bioconda channel, so from now on please use the bioconda channel for conda installs.

**Comment by dgaston** [comment]
Thanks Ryan!
