### ISSUE TITLE
Bedtool.map() not working - BedTool needs upgrading?

### ISSUE THREAD

**Issue by JeevG** [daler/pybedtools#219]
Hi

I'm new to using pybedtools so apologies if this is very simple! I have a bed file with intervals in the genome (transcription start sites). I then have a bedgraph file with expression data over the genome. I want a quick way of extracting, for each interval in the bed file, the average of that window in the bedgraph file, and wanted to do it in python.
The map() function looked liked exactly what I needed (http://bedtools.readthedocs.io/en/latest/content/tools/map.html) but when I try to use it I get the following errors:

if i try to call it on an object (should the object be the bed or bedgraph file?) like these: 
positions = BedTool('gene_intervals.bed)
measures = BedTool('measures.bedgraph)

positions.map() or measures.map() give: 

"mapBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

Can I upgrade the version of BedTool that pyBedTool is pointing to? Or is there another way to achieve what I'm trying to do

**Comment by daler** [comment]
`bedtools map` is probably the best way to do what you describe. However you'll need a recent version of bedtools that supports it. The easiest way is with bioconda (https://bioconda.github.io), since then you can do:

```
conda install bedtools pybedtools
```

to get recent versions of both.

In general, pybedtools will use whatever BEDTools is on your path, so upgrading your BEDTools version will be picked up automatically by pybedtools.
