### ISSUE TITLE
Strand specific merge does not keep strand information

### ISSUE THREAD

**Issue by sohrabi1** [daler/pybedtools#230]
Hi,

I came across this problem when using merge() function while keeping strandedness for a BedTool object. On the command line it can be done like this and works fine:
```
bedtools merge -s -c 6 -o distinct -i genes.bed 
```
But running the equivalent command in python does not keep the strand information in the pybed object:

```python
merged_genes = genes.merge(s = True, c = 6, o = 'distinct')
merged_genes[0].strand
> '.'
```

I believe this is because the strand will be on the third column of bedtools output and additional columns specified by -c are added afterwards. I found a quick and dirty way to solve it by adding another column before but it would be helpful if the output of merge is corrected .

```python
merged_genes = genes.merge(s = True, c = '5,6', o = 'distinct')
merged_genes[0].strand
> '+'
```
Thanks a lot!
Salma

**Comment by daler** [comment]
Hi Salma, thanks for reporting. "strand" in a BED file is the 6th column; the output from merge is only 5 columns:

```
$ cat a.bed
chr1    1       100     feature1        0       +
chr1    100     200     feature2        0       +
chr1    150     500     feature3        0       -
chr1    900     950     feature4        0       +
```
```
$ bedtools merge -s -c 6 -o distinct -i a.bed
chr1    1       200     +       +
chr1    150     500     -       -
chr1    900     950     +       +
```

The best way to handle non-standard BED files is to use the positional indexing rather than named attributes, so instead of 

```python
merged_genes[0].strand
```
you could use

```python
merged_genes[0][3]
```

**Comment by ewallace** [comment]
I'd like to request reopening this (same as #106 ) because the merged information does have a strand, it's just not accessible. Thus, I spent hours debugging code that worked fine on gff intervals but failed only on -strand merged inputs.

```python
import pybedtools

bedfn = pybedtools.example_filename('a.bed')
myBedTool = pybedtools.BedTool(bedfn)

print myBedTool
```
```
chr1	1	100	feature1	0	+
chr1	100	200	feature2	0	+
chr1	150	500	feature3	0	-
chr1	900	950	feature4	0	+
```
```python
print myBedTool[0].strand
```
```
+
```
Now we merge, and the printed object contains strand info.
```python
myMergedTool = myBedTool.merge(d=1,s=True)

print myMergedTool
```
```
chr1	1	200	+
chr1	150	500	-
chr1	900	950	+
```
Yet that info is not accessible to strand.
```python
print myMergedTool[0].strand
```
```
.
```
This would be very convenient. The essence is that stranded intervals should behave consistently.

It would have been easier to fix if an add_strand function, as discussed in #62 and #100, were in the API.

**Comment by daler** [comment]
Hi @ewallace - 

The behavior of `merge` is dependent on the installed version of BEDTools, and this behavior has changed in recent versions (see https://github.com/arq5x/bedtools2/issues/607). While it would be possible (and convenient) for pybedtools to detect on the fly whether or not a field contains a strand-like character, I would prefer not to do this since it would be too much of a performance hit in the general case. I think it's reasonable to assume correctly-formatted BED files when accessing by named attribute. That is, intervals encoding strand information to be accessed by the `.strand` attribute should be at least BED6 (chrom, start, stop, name, score, strand) and have the strand in the 6th column. It so happens `bedtools merge` from the version of BEDTools you have installed does not output correctly-formatted BED files when run in stranded mode.

That said, you can use

```python
myMergedTool[0][3]
```
to access the strand information encoded in the 4th field using integer indexing rather than named attributes.

**Comment by ewallace** [comment]
Hi @daler,
Thanks for taking a look at this. I updated my Bedtools and pybedtools, and the (s=True) or (S="+") options are now not producing a strand in the output bed. You're right that this is a bedtools merge issue, not a pybedtools issue.

I have a workaround for my application that involves adding strand information from a related object.
