### ISSUE TITLE
Why does pybedtools.contrib.IntersectionMatrix write to stdout instead of returning a pointer to a tmp file, like the rest of pybedtools? 

### ISSUE THREAD

**Issue by zfrenchee** [daler/pybedtools#237]

**Comment by daler** [comment]
Short answer: no reason.

Longer answer: this part of pybedtools has not been touched for a while. Since it was written, other algorithms have been developed (e.g., GAT, IntervalStats, bedtools jaccard, bedtools fisher). This reminds me that I need to deprecate this module, and you probably shouldn't use it. Instead you might want to have a look at https://github.com/lcdb/lcdb-wf, specifically the colocalization workflow at https://github.com/lcdb/lcdb-wf/blob/master/workflows/colocalization/Snakefile. This will perform *much* better, can be submitted to a cluster, runs multiple algorithms, and includes heatmap plotting, and is the current way I do many pairwise comparisons and as such is better maintained.

**Comment by zfrenchee** [comment]
@daler, while I have you for a moment: if you had bed peaks from a number of case/control ATAC or ChIP experiments, and you wanted to build a matrix of peaks by cell lines, how would you do it? I was thinking of getting some sort of overlapping "union" of all the peaks and then intersect each file with that union set. Where should I go looking for this? Or is there a better way of doing this kind of analysis in the first place you know of? Thanks!

**Comment by daler** [comment]
If you're asking about identifying classes of sites across all possible combinations of conditions, I generally use "binary heatmaps" for this, which plot the output of `bedtools multiinter`. See https://gist.github.com/daler/07eb1a95f1e4639f22bd for a working example.

You might want to study the toy example here to get a feel for the algorithm, which at first can seem non-intuitive: https://gist.github.com/daler/24227fed6f5fbcfbdd29646a653a9cca

When you get into the details of multiple intersections, things get tricky. In particular, how to handle nested peaks or a peak in one file that overlaps multiple in another file. `bedtools multiinter` seems to make reasonable choices about these cases which is why I prefer it. Your union approach should work as well, but I don't know of any off-the-shelf solution for that.

**Comment by zfrenchee** [comment]
@daler last question: Can you disambiguate `multiinter` (which is *maybe* deprecated in bedtools, but still documented in pybedtools) from `bedtools intersect -wao` which seems to have superseded multiinter?

> As of version 2.21.0, the intersect tool can accept multiple files for the -b option. This allows one to identify overlaps between a single query (-a) file and multiple database files (-b) at once!

I'm new to both bedtools and pybedtools so slightly confused about the history here.

**Comment by daler** [comment]
I believe the main difference is that `multiinter` is for getting the full combinatorial classes (for factors A, B, C, get: A not B not C, B not A not C, C not B not A, A and B not C, A and C not B, B and C not A, A and B and C) while `intersect` is for when you want to focus on one (e.g. you care about A with the others or not, but don't necessarily care about B and C with each other).
