### ISSUE TITLE
problem with subtract toy example

### ISSUE THREAD

**Issue by cajanegra1** [daler/pybedtools#244]
Sorry if this has already been posted; I looked around and could not find it.

Take a look at your toy example for using subtract:

```
a = pybedtools.example_bedtool('a.bed')
b = pybedtools.example_bedtool('b.bed')
a.head()
chr1	1	100	feature1	0	+
chr1	100	200	feature2	0	+
chr1	150	500	feature3	0	-
chr1	900	950	feature4	0	+
b.head()
chr1	155	200	feature5	0	-
chr1	800	901	feature6	0	+
s = a.subtract(b)
s.head()
chr1	1	100	feature1	0	+
chr1	100	155	feature2	0	+
chr1	150	155	feature3	0	-
chr1	200	500	feature3	0	-
chr1	901	950	feature4	0	+
```

Check out the second interval in `a`; I don't see anything that should be subtracted from it (given the strands), yet the subtraction `s` only captures part of it, namely `chr1	100	155	feature2	0	+`. I would say this interval should be the original `chr1	100	200	feature2	0	+`, without any part subtracted.

Am I missing something?

Thanks.

**Comment by daler** [comment]
Since this part of pybedtools is largely a wrapper for BEDTools, this is kind of a bedtools question, but by default `bedtools subtract` is not strand-aware. If you'd like it to be strand-aware, use `-s` from the command line, or in pybedtools use `s=True` when calling `BedTool.subtract`:

```
a.subtract(b, s=True).head()
chr1    1      100     feature1        0       +
chr1   100     200     feature2        0       +
chr1   150     155     feature3        0       -
chr1   200     500     feature3        0       -
chr1   901     950     feature4        0       +
```

In this case the second feature is the full, original `chr1   100     200     feature2        0       +`, as you're expecting.

**Comment by cajanegra1** [comment]
Makes sense. Thanks a lot Ryan.
