### ISSUE TITLE
pybedtools will not accept mac line endings 

### ISSUE THREAD

**Issue by roxyisat-rex** [daler/pybedtools#297]
![image](https://user-images.githubusercontent.com/53938505/65715060-49d52d80-e094-11e9-811a-819a9d82587b.png)

![image](https://user-images.githubusercontent.com/53938505/65714279-b18a7900-e092-11e9-87f7-b1481d08484a.png)

**Comment by daler** [comment]
Thanks for reporting. This is BEDTools itself causing the error -- if `a.bed` is a file containing only `\r` line endings, the following will also fail on the command line:

```bash
bedtools intersect -a a.bed -b a.bed
```
gives:

```
Error: unable to open file or unable to determine types for file a.bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
```
By the way, instead of opening in a text editor (which can be costly for large files), you can use 

```bash
tr '\r' '\n' < mac.bed > unix.bed
```
which should be a lot faster.
